### ISSUE TITLE
installs with the error "TypeError: Cannot read property 'viewBox' of undefined"

### ISSUE THREAD

**Issue by Tornike-Kiknadze** [VictorCazanave/react-svg-map#38]
The App does not install correctly, it gives errors

**Comment by VictorCazanave** [comment]
Hello @Tornike-Kiknadze !
Which [map](https://github.com/VictorCazanave/react-svg-map#maps) do you use? Could you show your (simplified) code please?

**Comment by Tornike-Kiknadze** [comment]
I figured out I had not installed the maps apparently they need to be installed separately...

**Comment by VictorCazanave** [comment]
Yes, [since v2.0.0 the maps are in independent packages](https://github.com/VictorCazanave/react-svg-map#warning-breaking-change-from-v1) to avoid to download all the maps and make them re-usable in other projects.
