### ISSUE TITLE
Is there any option to define default checked locations?

### ISSUE THREAD

**Issue by rommelmamedov** [VictorCazanave/react-svg-map#39]

**Comment by VictorCazanave** [comment]
Currently there isn't any property to set the checked locations, but it may be a good idea to add it.

If you know how to do it, feel free to open a PR! Otherwise I'll try to do it next week.

**Comment by rommelmamedov** [comment]
Thanks for the quick response! I'll try to check up the source code for in order to implement it.

**Comment by VictorCazanave** [comment]
@rommelmamedov before merging the PR, what do you think of the new props `selectedLocationId` (for `RadioSVGMap`) and `selectedLocationIds` (for `CheckboxSVGMap`)? Are they convenient enough for your use case?

**Comment by rommelmamedov** [comment]
> @rommelmamedov before merging the PR, what do you think of the new props `selectedLocationId` (for `RadioSVGMap`) and `selectedLocationIds` (for `CheckboxSVGMap`)? Are they convenient enough for your use case?

Yes, I think they are totally okay.
