### ISSUE TITLE
Disable click behaviour on Checkbox map

### ISSUE THREAD

**Issue by thomasbritton** [VictorCazanave/react-svg-map#45]
Hi, 

Is it possible to disable all click behaviour for the Checkbox map?

I have a world map and I am currently highlighting certain countries using the `selectedLocationIds` but I do not want the click behaviour to fill / unfill the countries upon clicking. 

Is there a better way to approach this other than using the Checkbox map?

Thanks

**Comment by VictorCazanave** [comment]
Hello,

I think you can use the `SVGMap` component and pass a function to the `locationClassName` prop to highlight certain countries.
You can have a look at the [heat map example](https://github.com/VictorCazanave/react-svg-map/blob/master/examples/src/components/tooltip-heat-map.jsx#L40) and customize the function to fit your needs.

Feel free to re-open the issue, if you have more questions about it.
