### ISSUE TITLE
Is there anyway to zoom in on a particular path onClick?

### ISSUE THREAD

**Issue by bkrmalick** [VictorCazanave/react-svg-map#48]
For the below example. Is there any way to zoom onto a state when clicking on it? 

![image](https://user-images.githubusercontent.com/45543786/89669224-f8faac00-d8d6-11ea-8a9e-11582e66c4bd.png)

**Comment by VictorCazanave** [comment]
I'm not sure whether this is possible. You may try to play with CSS to hide the other states and scale the map (`transform: scale()`) 🤔

**Comment by bkrmalick** [comment]
I've been able to use https://github.com/chrvadala/react-svg-pan-zoom as a wrapper.

Thanks.
