### ISSUE TITLE
Can we get onLocationClick to CheckboxSVGMap

### ISSUE THREAD

**Issue by pkocak** [VictorCazanave/react-svg-map#50]
I have tried onLocationFocus and onLocationBlur as provided but they create some bugs in my project. It would be perfect if i can get onLocationClick

**Comment by VictorCazanave** [comment]
Can you use `onChange` instead?
Currently `onLocationClick` of `SVGMap` is used by `CheckboxSVGMap` to toggle the location, then calls `onChange` if provided.

**Comment by pkocak** [comment]
Thanks for the reply. I'll give it a try :)

**Comment by VictorCazanave** [comment]
@pkocak  if your issue is not fixed, feel free to re-open it.
