### ISSUE TITLE
how add terrain type

### ISSUE THREAD

**Issue by raulcesar54** [VictorCazanave/react-svg-map#52]
how i add terrain type, example: 
![image](https://user-images.githubusercontent.com/50491912/117687205-8ed4a780-b185-11eb-8a01-37ee1afd8282.png)

the  horizontal and vertical line, identify the terrain type

**Comment by VictorCazanave** [comment]
This component supports SVG files that contain only `<path>` tags. You can look at [svg-maps](https://github.com/VictorCazanave/svg-maps) to see examples of working maps.

**Comment by raulcesar54** [comment]
I resolve this with fill, childrenBefore i pass <image id='xxx' /> on class i pass fill='#xxx',
