### ISSUE TITLE
Based on condition i want to select the state 

### ISSUE THREAD

**Issue by deepghuge36** [VictorCazanave/react-svg-map#56]
I have the condition on the basis I want to select the state and show that state is selected how I can do that?

 function handleclick(id, stateName) {
    console.log("im clilck");
    setStateCode(id);
    setStateName(stateName);
    setDisplayState(stateName);
}

**Comment by VictorCazanave** [comment]
Hi @deepghuge36,
It looks similar to the [demo](https://victorcazanave.github.io/react-svg-map/). Have you looked at the [examples' source code](https://github.com/VictorCazanave/react-svg-map/tree/master/examples/src)? 
If this is not what you want, please detail your needs and share more code (in https://codesandbox.io/ for example).
